### ISSUE TITLE
Link to old project in README

### ISSUE THREAD

**Issue by phil-davis** [friends-of-phpspec/phpspec-expect#3]
What should happen about https://github.com/friends-of-phpspec/phpspec-expect/commit/36a1ff9b40ac8be55df7182a286df736647bf6d2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R33 ?

`README.md` has a link to the old repo.

**Comment by jaylinski** [comment]
@phil-davis I'm not sure I understand the question. The link is still there. The commit just updates the year form 2013 to 2017 (I made a typo in a previous commit).

It's an attribution to the previous author. Same as here: https://github.com/friends-of-phpspec/phpspec-code-coverage#authors

**Comment by phil-davis** [comment]
> It's an attribution to the previous author

True, I guess a link in the README is fine. People should not be confused and follow that link to use that repo, it is now just history.
