### ISSUE TITLE
Missing file and line makes it difficult to figure out where the failure is

### ISSUE THREAD

**Issue by walterdolce** [friends-of-phpspec/phpspec-expect#4]
This is a clone of https://github.com/BossaConsulting/phpspec2-expect/issues/46

Hi. 
In a scenario like the one below, where `$foo` and/or `$baz` return `00000`:
```
# code

expect($foo)->notToBe('');

# more code

expect($baz)->notToBe('');
```

The error one gets (as expected) is:
```
Expected <value>""</value>, but got <value>"00000"</value>. (PhpSpec\Exception\Example\NotEqualException)
```

The fact that `__FILE__` and `__LINE__` is missing makes it painful for engineers to figure out where exactly the failure is. One has to resort to using `var_dump`, etc to get a clue.

This is basic yet fundamental info which should be included in the errors.

**Comment by jaylinski** [comment]
@walterdolce I'm not quite sure if I understand the issue.

If one of my `expect()` tests fail, I'm getting the exact location when running `phpspec run --verbose`:

![Bildschirmfoto vom 2021-01-21 17-36-47](https://user-images.githubusercontent.com/1668766/105381668-8aed3b80-5c0f-11eb-8a10-b39441761cbf.png)

Can you provide a detailed example?

**Comment by jaylinski** [comment]
Please reopen if there is still an issue.
